build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.11.4
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"


linux_x86_task:
  name: Build Linux x86 wheels
  env:
    CIBW_MANYLINUX_X86_64_IMAGE: dockcross/manylinux_2_28-x64:latest
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y gcc-c++ libpng-devel libpng
      pip install cmake ninja
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 8G
  install_pre_requirements_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update
   - apt-get install -y python3-dev python-is-python3
  <<: *BUILD_AND_STORE_WHEELS