build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.11.4
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

apt-install:
  steps:
    - run:
        name: Install apt packages
        command: |
          apt-get update
          apt-get install -y --no-install-recommends apt-transport-https build-essential ca-certificates curl git gnupg libpng-dev software-properties-common


linux_x86_task:
  name: Build Linux x86 wheels
  docker:
    image: continuumio/miniconda3:4.12.0
  resource_class: medium

  steps:
    - apt-install
    
    - run:
        name: update/install python modules
        command: |
          conda install -y -c conda-forge cmake ninja
          conda env update -n base --file ./environment.yml --prune

  <<: *BUILD_AND_STORE_WHEELS


linux_aarch64_task:
  name: Build Linux aarch64 wheels
  docker:
    image: continuumio/miniconda3:4.12.0
  resource_class: arm.medium

  steps:
    - apt-install
    
    - run:
        name: update/install python modules
        command: |
          conda install -y -c conda-forge cmake ninja
          conda env update -n base --file ./environment.yml --prune
  <<: *BUILD_AND_STORE_WHEELS


# macos_arm64_task:
#   name: Build macOS arm64 wheels.
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-monterey-xcode

#   env:
#     PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
#   install_pre_requirements_script:
#     - brew install python@3.10 cmake libpng ninja
#     - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
#   <<: *BUILD_AND_STORE_WHEELS
