build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.11.4
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"


linux_x86_task:
  name: Build Linux x86 wheels
  timeout_in: 120m
  env:
    matrix:
      - CIBW_BUILD: "cp39-manylinux*"
      - CIBW_BUILD: "cp310-manylinux*"
    CIBW_MANYLINUX_X86_64_IMAGE: dockcross/manylinux_2_28-x64:latest
    CIBW_ARCHS_LINUX: "auto64"
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y gcc-c++ libpng-devel libpng
      pip install cmake ninja
    CIBW_BUILD_VERBOSITY: 3
    # CIBW_ENVIRONMENT: PIP_GLOBAL_OPTION="build_ext -j4"
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 8G
  install_pre_requirements_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update
   - apt-get install -y python3-dev python-is-python3
  <<: *BUILD_AND_STORE_WHEELS


linux_aarch64_task:
  name: Build Linux aarch64 wheels
  timeout_in: 120m
  env:
    matrix:
      - CIBW_BUILD: "cp39-manylinux*"
      - CIBW_BUILD: "cp310-manylinux*"
    CIBW_ARCHS_LINUX: "auto"
    CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_28_aarch64:latest
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y gcc-c++ libpng-devel libpng
      pip install cmake ninja
    CIBW_BUILD_VERBOSITY: 3
    # CIBW_ENVIRONMENT: PIP_GLOBAL_OPTION="build_ext -j4"
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 4
    memory: 8G
  install_pre_requirements_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update
   - apt-get install -y python3-dev python-is-python3
  <<: *BUILD_AND_STORE_WHEELS


# docker_builder:
#   name: Build x86 docker images
#   timeout_in: 120m
#   env:
#     DOCKER_USERNAME: ENCRYPTED[!09cc4caa9cb6dbf5af7f2630c1d74076abd1cff6bb103db2bae45d022f28404e040ee5db21f076f70decb59a294780ab!]
#     DOCKER_PASSWORD: ENCRYPTED[!3eccd194e0044101db2d7379d2d95f9255e3493c7ae72a6843ca83a6547ea271541271d77858a2ffd30f61ab68514a64!]
#     TAG: cirrus-ci
#     CIBW_BUILD_VERBOSITY: 3
#   setup_script:
#     - docker --version
#   build_script: docker build --tag noelmni/antspy:$TAG .
#   login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#   push_script: docker push noelmni/antspy:$TAG


# docker_builder:
#   name: Build aarch64 docker images
#   timeout_in: 120m
#   env:
#     CIRRUS_ARCH: arm64
#     DOCKER_USERNAME: ENCRYPTED[!09cc4caa9cb6dbf5af7f2630c1d74076abd1cff6bb103db2bae45d022f28404e040ee5db21f076f70decb59a294780ab!]
#     DOCKER_PASSWORD: ENCRYPTED[!3eccd194e0044101db2d7379d2d95f9255e3493c7ae72a6843ca83a6547ea271541271d77858a2ffd30f61ab68514a64!]
#     TAG: cirrus-ci
#     CIBW_BUILD_VERBOSITY: 3
#   setup_script:
#     - docker --version
#   build_script: docker build --tag noelmni/antspy:$TAG-$CIRRUS_ARCH .
#   login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#   push_script: docker push noelmni/antspy:$TAG-$CIRRUS_ARCH
