build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.11.4
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"


linux_x86_task:
  name: Build Linux x86 wheels
  timeout_in: 120m
  env:
    CIBW_BUILD: "cp3[6,7,8,9,10,11]-manylinux*"
    CIBW_MANYLINUX_X86_64_IMAGE: dockcross/manylinux_2_28-x64:latest
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y gcc-c++ libpng-devel libpng
      pip install cmake ninja
    CIBW_BUILD_VERBOSITY: 3
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 8G
  install_pre_requirements_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update
   - apt-get install -y python3-dev python-is-python3
  <<: *BUILD_AND_STORE_WHEELS


linux_aarch64_task:
  name: Build Linux aarch64 wheels
  timeout_in: 120m
  env:
    CIBW_BUILD: "cp3[6,7,8,9,10,11]-manylinux*"
    CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_28_aarch64:latest
    CIBW_BEFORE_ALL_LINUX: |
      yum install -y gcc-c++ libpng-devel libpng
      pip install cmake ninja
    CIBW_BUILD_VERBOSITY: 3
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 4
    memory: 8G
  install_pre_requirements_script:
   - export DEBIAN_FRONTEND=noninteractive
   - apt-get update
   - apt-get install -y python3-dev python-is-python3
  <<: *BUILD_AND_STORE_WHEELS