# TODO: pin dependency versions
name: antspy
channels:
  - default
  - conda-forge
dependencies:
- pandas
- pyyaml
- numpy
- scikit-image
- scikit-learn
- statsmodels
- webcolors
- matplotlib
- Pillow
- nibabel
