name: ci-pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Updates or changes to this, or the runner OS or arch will invalidate the cache
  python_version: "3.12" # Python version to use for testing - update when needed

jobs:
  test:
    runs-on: ubuntu-22.04
    # Default shell needs to be bash for conda
    # https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#important
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5
        with:
            channels: conda-forge
            conda-remove-defaults: true
            miniforge-version: latest
            python-version: ${{ env.python_version }}
            auto-update-conda: true
            activate-environment: antspy-env

      - name: Checkout code
        uses: actions/checkout@v6
        with:
            path: antspy-pr

      - name: Install dependencies and ANTsPy from PR
        run: |
            conda info
            which python
            python --version
            python -m pip --version

            conda install -y coverage pip setuptools wheel packaging
            python -m pip install --upgrade pip setuptools wheel 'packaging>=24'

            python -m pip install SimpleITK nibabel
            python -m pip install ./antspy-pr

            python -c "import sys, packaging; print(sys.executable); print(packaging.__version__, packaging.__file__)"
            conda list

      - name: Run tests
        run: |
          conda activate antspy-env
          bash antspy-pr/tests/run_tests.sh -c

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: antspy-pr/tests/coverage.xml
