name: push
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5

      - name: Install package
        run: python -m pip install .

      - name: Unit tests
        run: tests/run_tests.sh --coverage

      - name: Coverage
        run: coveralls --service=github

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
