on:
  push:
    branches:
      - master

  workflow_dispatch:

name: codecov

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5

      - name: Install package
        run: python -m pip install .

      - name: Install coverage
        run: python -m pip install coverage

      - name: Find installed package path
        id: find_package_path
        run: |
          echo "PACKAGE_PATH=$(python tests/find_package_path.py)" >> $GITHUB_ENV

      - name: Unit tests
        run: tests/run_tests.sh -c -s ${PACKAGE_PATH}

      - name: Coveralls
        uses: coverallsapp/github-action@v2
